//! The HTTP capability's payload types.
//!
//! These ride *inside* `PluginResponse.output` as bincode, rather than as fields on
//! `PluginResponse` itself: that struct is shared by every plugin, and HTTP-specific
//! columns on it would be a domain leak into the fixed plugin ABI.

use facet::Facet;
use serde::{Deserialize, Serialize};

/// One HTTP header.
///
/// A named struct rather than a `(String, String)` tuple: the shared types contain no
/// tuples today, and tuple codegen into Swift/Kotlin is the least reliable corner of
/// serde-reflection.
#[derive(Facet, Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
#[repr(C)]
pub struct HttpHeader {
    pub name: String,
    pub value: String,
}

/// The result of an HTTP request.
#[derive(Facet, Serialize, Deserialize, Clone, Debug, PartialEq, Eq)]
#[repr(C)]
pub enum HttpOutcome {
    /// The server answered. `status` is the real HTTP status — 409 is distinguishable
    /// from 500.
    Response { status: u16, headers: Vec<HttpHeader>, body: Vec<u8> },
    /// No HTTP response was obtained, for any reason: chiefly network failure
    /// (offline, DNS, TLS, connection refused, timeout), but also a request that could
    /// not be attempted at all (unknown verb, malformed envelope). The defining
    /// property is that the server never answered, so no status exists.
    TransportError { message: String },
}

impl HttpOutcome {
    /// The HTTP status, or `None` when the server never answered.
    pub fn status(&self) -> Option<u16> {
        match self {
            Self::Response { status, .. } => Some(*status),
            Self::TransportError { .. } => None,
        }
    }

    /// True only for a 2xx response.
    pub fn is_success(&self) -> bool {
        matches!(self, Self::Response { status, .. } if (200..300).contains(status))
    }

    /// The raw response body; empty for a transport error.
    pub fn body(&self) -> &[u8] {
        match self {
            Self::Response { body, .. } => body,
            Self::TransportError { .. } => &[],
        }
    }

    /// The body as text, or `None` if it is not valid UTF-8 (or there is no body).
    pub fn text(&self) -> Option<&str> {
        std::str::from_utf8(self.body()).ok().filter(|_| matches!(self, Self::Response { .. }))
    }

    /// Look up a response header by name, case-insensitively.
    pub fn header(&self, name: &str) -> Option<&str> {
        match self {
            Self::Response { headers, .. } => headers
                .iter()
                .find(|h| h.name.eq_ignore_ascii_case(name))
                .map(|h| h.value.as_str()),
            Self::TransportError { .. } => None,
        }
    }

    /// Serialize for transport in `PluginResponse.output`.
    ///
    /// Uses crux's own FFI format rather than calling bincode directly. This is not
    /// incidental: crux pins bincode `=1.3` with `with_fixint_encoding()`, whereas
    /// bincode 2.x's `config::standard()` is *varint*. The two produce different
    /// bytes, and the Swift/Kotlin decoders generated by serde-generate expect crux's
    /// encoding — so hand-rolling this would silently yield garbage across the FFI.
    pub fn encode(&self) -> Vec<u8> {
        use crux_core::bridge::{BincodeFfiFormat, FfiFormat};
        let mut buffer = Vec::new();
        BincodeFfiFormat::serialize(&mut buffer, self).expect("encode HttpOutcome");
        buffer
    }

    /// Decode what a shell placed in `PluginResponse.output`.
    pub fn decode(bytes: &[u8]) -> Result<Self, String> {
        use crux_core::bridge::{BincodeFfiFormat, FfiFormat};
        BincodeFfiFormat::deserialize(bytes).map_err(|e| e.to_string())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn resp(status: u16, body: &str) -> HttpOutcome {
        HttpOutcome::Response {
            status,
            headers: vec![HttpHeader { name: "Content-Type".into(), value: "application/json".into() }],
            body: body.as_bytes().to_vec(),
        }
    }

    #[test]
    fn status_is_some_for_response_and_none_for_transport_error() {
        assert_eq!(resp(200, "").status(), Some(200));
        assert_eq!(HttpOutcome::TransportError { message: "offline".into() }.status(), None);
    }

    #[test]
    fn is_success_covers_exactly_2xx() {
        assert!(!resp(199, "").is_success());
        assert!(resp(200, "").is_success());
        assert!(resp(299, "").is_success());
        assert!(!resp(300, "").is_success());
        assert!(!resp(409, "").is_success());
        assert!(!HttpOutcome::TransportError { message: "x".into() }.is_success());
    }

    #[test]
    fn body_and_text_behave_on_valid_and_invalid_utf8() {
        assert_eq!(resp(200, "hi").body(), b"hi");
        assert_eq!(resp(200, "hi").text(), Some("hi"));

        let binary = HttpOutcome::Response { status: 200, headers: vec![], body: vec![0xff, 0xfe] };
        assert_eq!(binary.body(), &[0xff, 0xfe]);
        assert_eq!(binary.text(), None, "invalid UTF-8 must not panic or lossily convert");

        let err = HttpOutcome::TransportError { message: "x".into() };
        assert_eq!(err.body(), b"");
        assert_eq!(err.text(), None);
    }

    #[test]
    fn header_lookup_is_case_insensitive() {
        assert_eq!(resp(200, "").header("content-type"), Some("application/json"));
        assert_eq!(resp(200, "").header("CONTENT-TYPE"), Some("application/json"));
        assert_eq!(resp(200, "").header("missing"), None);
    }

    #[test]
    fn bincode_round_trips_both_variants() {
        for original in [
            resp(409, "conflict"),
            HttpOutcome::TransportError { message: "connection refused".into() },
        ] {
            let bytes = original.encode();
            assert_eq!(HttpOutcome::decode(&bytes).unwrap(), original);
        }
    }

    #[test]
    fn decode_rejects_garbage_without_panicking() {
        assert!(HttpOutcome::decode(&[0xff, 0xff, 0xff]).is_err());
    }
}
